[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
category = "Simulation"
title = "Isaac Flexiv Robot"
description = "Isaac Flexiv Robot Class"
authors = ["Flexiv"]
repository = ""
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.motion_generation" = {}
"omni.isaac.manipulators" = {}
"omni.isaac.nucleus" = {}

[[python.module]]
name = "omni.isaac.flexiv"
